---
title: "Predicting 2020 American Federal Election"
author: "Pamela De Vera, Hyoeun Park"
date: "11/02/2020"
output: pdf_document
---

```{r setup, echo=FALSE, message=FALSE, include = FALSE}
# Install any of the packages below if uninstalled:
## install.packages("tidyverse")
## install.packages("lme4")
## install.packages("arm")
## install.packages("knitr")
## install.packages("kableExtra")
## install.packages("readr")

# Libraries
library(tidyverse)
library(lme4)
library(arm)
library(knitr)
library(readr)
library(kableExtra)

knitr::opts_chunk$set(echo = FALSE, fig.align = 'center', message = FALSE)
```

```{r}
# Set working directory
## You may want to change this if you wish
setwd("~/Desktop/STA304/Problem Set 3/election_data")

# Loading in the cleaned survey Data
survey_data <- read_csv("~/outputs/survey_data.csv")

# Loading in the cleaned census Data
census_data <- read_csv("~/outputs/census_data.csv")

################################################################################

# Model
# Frequentist Multilevel Logistic Regression Model
## Random Intercept Model for Biden
pollmodel_Biden <- glmer(as.factor(vote_biden) ~ sex + age_group + 
race + is_hispanic + education_level + 
income_class + (1 | region), 
family = binomial, 
data = survey_data)

## Random Intercept Model for Trump
pollmodel_Trump <- glmer(as.factor(vote_trump) ~ sex + age_group + 
race + is_hispanic + education_level + 
income_class + (1 | region), 
family = binomial, 
data = survey_data)

# See regression output for Biden
summary(pollmodel_Biden)
ranef(pollmodel_Biden) # Coefficients of slope $\beta_{0j}$

# See regression output for Trump
summary(pollmodel_Trump)
ranef(pollmodel_Trump)

################################################################################

# Diagnostics
## Binned Residual Plot for Biden
binnedplot(fitted(pollmodel_Biden), 
           residuals(pollmodel_Biden, type = "response"), 
           xlab = "Expected Values", 
           ylab = "Average residual", 
           main = "Biden: Binned Residual Plot",
           sub = "Figure 1")

## Binned Residual Plot for Trump
binnedplot(fitted(pollmodel_Trump), 
           residuals(pollmodel_Trump, type = "response"), 
           xlab = "Expected Values", 
           ylab = "Average residual", 
           main = "Trump: Binned Residual Plot",
           sub = "Figure 2")

################################################################################

# Table of Regression Outputs of Both Models

regoutput <- tibble(coefficients = c("Intercept", "Northwest", "Midwest", "South", "West", 
"26-35", "36-45", "46-55", "56-65", "66-75", "76-85", "86-95", 
"Male", "Black", "Indigenous", "Other", "White", "Hispanic", 
"Master/Doctorate", "Primary/Secondary", "Low Income", "Middle Income"), 
b_estimates = c(0.9681, 0.1114, 0.0564, -0.2238, 0.0562, 
-0.3371, -0.3931, -0.6572, -0.3418, -0.2956, -0.5506, -0.7272, 
-0.4008, 1.0339, -1.0264, -0.3567, -0.7664, 0.3433, 
0.0235, -0.3217, 0.3341, 0.2344), 
b_pval = c("4.24x10^(-7)", "", "", "", "", 
"0.0030", "0.0005", "4.70x10^(-8)", "0.0034", "0.0172", "0.0072", "0.3120", 
"3.15x10^(-11)", "4.90x10^(-9)", "0.0004", "0.0589", "6.43x10^(-8)", "0.0004", 
"0.8034", "1.85x10^(-6)", "0.0006", "0.0100"), 
t_estimates = c(-1.1977, -0.1272, -0.0492, 0.2672, -0.0906, 
0.4406, 0.5927, 0.7820, 0.5896, 0.5363, 0.7913, 1.0882, 
0.3749, -1.3722, 0.8021, 0.2186, 0.7680, -0.3454, 
-0.0150, 0.2885, -0.4685, -0.3252), 
t_pval = c("3.13x10^(-9)", "", "", "", "", 
"0.0002", "5.52^10x(-7)", "3.80x10^(-10)", "1.16x10^(-6)", "3.06x10^(-5)", "0.0001", "0.1304", 
"8.77x10^(-10)", "2.24x10^(-12)", "0.0059", "0.2668", "1.65x10^(-7)", "0.0005", 
"0.8746", "2.46x10^(-5)", "1.68x10^(-6)", "0.0004"))

table1 <- kable(regoutput, caption = "Model Summary", 
col.names = c("Coefficients", "Estimates", "P-values", "Estimates", "P-values")) %>% 
pack_rows("Intercept: Region", 1, 5) %>% 
pack_rows("Age Group", 6, 12) %>% 
pack_rows("Sex", 13, 13) %>% 
pack_rows("Race", 14, 17) %>% 
pack_rows("Hispanic", 18, 18) %>% 
pack_rows("Education Level", 19, 20) %>% 
pack_rows("Income Level", 21, 22) %>% 
row_spec(0, bold = TRUE) %>% 
kable_classic_2(full_width = F) %>% 
add_header_above(c(" " = 1, "Joe Biden" = 2, "Donald Trump" = 2))

## See Table 1
table1
################################################################################

# Post-stratification Calculation: Biden

## Create a variable in the dataset for the log odds based on our model
census_data$logestimate_Biden <-
  pollmodel_Biden %>%
  predict(newdata = census_data)

## Create a variable in the dataset with the probabiity estimate that a cell will
## vote for Biden
census_data$estimate_Biden <-
  exp(census_data$logestimate_Biden)/(1+exp(census_data$logestimate_Biden))

## Post stratification calculation
census_data$prop_Biden <-
  census_data$estimate_Biden*census_data$n

## See post-stratification result
## yhat_Biden := proportion of Americans voting for Joe Biden
yhat_Biden <- sum(census_data$prop_Biden)/sum(census_data$n)

##########################################

# Post-stratification Calculation: Trump

## Create a variable in the dataset for the log odds based on our model
census_data$logestimate_Trump <-
  pollmodel_Trump %>%
  predict(newdata = census_data)

## Create a variable in the dataset with the probabiity estimate that a cell will
## vote for Trump
census_data$estimate_Trump <-
  exp(census_data$logestimate_Trump)/(1+exp(census_data$logestimate_Trump))

## Post stratification calculation
census_data$prop_Trump <-
  census_data$estimate_Trump*census_data$n

## See post-stratification result
## yhat_Trump := proportion of Americans voting for Donald Trump
yhat_Trump <- sum(census_data$prop_Trump)/sum(census_data$n)
```
